### ISSUE TITLE
高频齿音重，有点失真

### ISSUE THREAD

**Issue by Cheneng** [liuhuang31/hifigan-sr#1]
听了下demo感觉高频齿音比较重，有点失真，可能是上升采样率过高？

**Comment by liuhuang31** [comment]
@Cheneng 你好：
1. 模型训练不充分，只训练到120k，这个应该是主要原因
2. 模型用的是config_v2，模型参数量少了点，但不是主要原因。
你可以听听这个模型的，训练到300k，效果比较不错 [hiftnet-sr](https://github.com/liuhuang31/HiFTNet-sr)

**Comment by Cheneng** [comment]
感谢回复 效果很好
